// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.ABAC.Infrastructure.Persistence;

#nullable disable

namespace Sistema.ABAC.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AbacDbContext))]
    [Migration("20260211112153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.AccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador de la acción que se intentó realizar (opcional)");

                    b.Property<string>("Context")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Información contextual adicional en formato JSON");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Fecha y hora del intento de acceso (timestamp)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasComment("Dirección IP desde la cual se realizó la solicitud");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicador de eliminación lógica (soft delete)");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador de la política que produjo la decisión (opcional)");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Razón detallada de la decisión");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del recurso al que se intentó acceder (opcional)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Resultado de la evaluación (Permit, Deny, Error, NotApplicable)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de última actualización del registro");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del usuario que intentó acceder");

                    b.HasKey("Id");

                    b.HasIndex("ActionId")
                        .HasDatabaseName("IX_AccessLogs_ActionId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AccessLogs_CreatedAt");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("IX_AccessLogs_IpAddress");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_AccessLogs_IsDeleted");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("IX_AccessLogs_PolicyId");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("IX_AccessLogs_ResourceId");

                    b.HasIndex("Result")
                        .HasDatabaseName("IX_AccessLogs_Result");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AccessLogs_UserId");

                    b.HasIndex("ResourceId", "CreatedAt")
                        .HasDatabaseName("IX_AccessLogs_ResourceId_CreatedAt");

                    b.HasIndex("Result", "CreatedAt")
                        .HasDatabaseName("IX_AccessLogs_Result_CreatedAt");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_AccessLogs_UserId_CreatedAt");

                    b.ToTable("AccessLogs", (string)null);
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.Action", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Código único de la acción usado en evaluación");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Fecha de creación del registro");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Descripción detallada de lo que permite hacer esta acción");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicador de eliminación lógica (soft delete)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nombre descriptivo de la acción");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de última actualización del registro");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Actions_Code")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Actions_IsDeleted");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Actions_Name");

                    b.ToTable("Actions", (string)null);
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.Attribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Fecha de creación del registro");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Descripción detallada del propósito del atributo");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicador de eliminación lógica (soft delete)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Clave única del atributo usada en evaluación de políticas");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nombre descriptivo del atributo");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Tipo de dato del atributo (String, Number, Boolean, DateTime)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de última actualización del registro");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Attributes_IsDeleted");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_Attributes_Key")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Attributes_Name");

                    b.ToTable("Attributes", (string)null);
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Fecha de creación del registro");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Descripción detallada del propósito de la política");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Efecto de la política cuando se cumplen las condiciones (Permit o Deny)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica si la política está activa y debe ser evaluada");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicador de eliminación lógica (soft delete)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre descriptivo de la política");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100)
                        .HasComment("Prioridad numérica para resolver conflictos (mayor = más prioritaria)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de última actualización del registro");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Policies_IsActive");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Policies_IsDeleted");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Policies_Name");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_Policies_Priority");

                    b.HasIndex("IsActive", "IsDeleted", "Priority")
                        .HasDatabaseName("IX_Policies_IsActive_IsDeleted_Priority")
                        .HasFilter("[IsActive] = 1 AND [IsDeleted] = 0");

                    b.ToTable("Policies", (string)null);
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.PolicyAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador de la acción");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Fecha de creación del registro");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicador de eliminación lógica (soft delete)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador de la política");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de última actualización del registro");

                    b.HasKey("Id");

                    b.HasIndex("ActionId")
                        .HasDatabaseName("IX_PolicyActions_ActionId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_PolicyActions_IsDeleted");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("IX_PolicyActions_PolicyId");

                    b.HasIndex("PolicyId", "ActionId")
                        .IsUnique()
                        .HasDatabaseName("IX_PolicyActions_PolicyId_ActionId")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("PolicyActions", (string)null);
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.PolicyCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Clave del atributo que se evaluará");

                    b.Property<string>("AttributeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Tipo de atributo: Subject, Resource o Environment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Fecha de creación del registro");

                    b.Property<string>("ExpectedValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Valor esperado contra el cual se comparará el atributo");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicador de eliminación lógica (soft delete)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Operador de comparación (Equals, NotEquals, GreaterThan, etc.)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador de la política a la que pertenece esta condición");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de última actualización del registro");

                    b.HasKey("Id");

                    b.HasIndex("AttributeKey")
                        .HasDatabaseName("IX_PolicyConditions_AttributeKey");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_PolicyConditions_IsDeleted");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("IX_PolicyConditions_PolicyId");

                    b.HasIndex("PolicyId", "AttributeType")
                        .HasDatabaseName("IX_PolicyConditions_PolicyId_AttributeType");

                    b.ToTable("PolicyConditions", (string)null);
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Fecha de creación del registro");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Descripción detallada del recurso y su contenido");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicador de eliminación lógica (soft delete)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre descriptivo del recurso");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Tipo o categoría del recurso (documento, endpoint, vista, etc.)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de última actualización del registro");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Resources_IsDeleted");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Resources_Name");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Resources_Type");

                    b.HasIndex("Type", "IsDeleted")
                        .HasDatabaseName("IX_Resources_Type_IsDeleted");

                    b.ToTable("Resources", (string)null);
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.ResourceAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del atributo que se asigna");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Fecha de creación del registro");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicador de eliminación lógica (soft delete)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del recurso al que se asigna el atributo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de última actualización del registro");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Valor concreto del atributo para este recurso");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("IX_ResourceAttributes_AttributeId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ResourceAttributes_IsDeleted");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("IX_ResourceAttributes_ResourceId");

                    b.HasIndex("ResourceId", "AttributeId")
                        .HasDatabaseName("IX_ResourceAttributes_ResourceId_AttributeId");

                    b.ToTable("ResourceAttributes", (string)null);
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Fecha y hora de creación del usuario");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nombre del usuario");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicador de eliminación lógica (soft delete)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Apellido del usuario");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha y hora de última actualización del usuario");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Users_CreatedAt");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Users_IsDeleted");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_Users_FirstName_LastName");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.UserAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del atributo que se asigna");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Fecha de creación del registro");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicador de eliminación lógica (soft delete)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de última actualización del registro");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador del usuario al que se asigna el atributo");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha desde la cual este valor es válido (null = desde siempre)");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha hasta la cual este valor es válido (null = indefinidamente)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Valor concreto del atributo para este usuario");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("IX_UserAttributes_AttributeId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_UserAttributes_IsDeleted");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserAttributes_UserId");

                    b.HasIndex("UserId", "AttributeId")
                        .HasDatabaseName("IX_UserAttributes_UserId_AttributeId");

                    b.HasIndex("ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_UserAttributes_ValidFrom_ValidTo");

                    b.ToTable("UserAttributes", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Sistema.ABAC.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Sistema.ABAC.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema.ABAC.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Sistema.ABAC.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.AccessLog", b =>
                {
                    b.HasOne("Sistema.ABAC.Domain.Entities.Action", "Action")
                        .WithMany("AccessLogs")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sistema.ABAC.Domain.Entities.Policy", "Policy")
                        .WithMany("AccessLogs")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sistema.ABAC.Domain.Entities.Resource", "Resource")
                        .WithMany("AccessLogs")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sistema.ABAC.Domain.Entities.User", "User")
                        .WithMany("AccessLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Policy");

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.PolicyAction", b =>
                {
                    b.HasOne("Sistema.ABAC.Domain.Entities.Action", "Action")
                        .WithMany("PolicyActions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistema.ABAC.Domain.Entities.Policy", "Policy")
                        .WithMany("PolicyActions")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.PolicyCondition", b =>
                {
                    b.HasOne("Sistema.ABAC.Domain.Entities.Policy", "Policy")
                        .WithMany("Conditions")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.ResourceAttribute", b =>
                {
                    b.HasOne("Sistema.ABAC.Domain.Entities.Attribute", "Attribute")
                        .WithMany("ResourceAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistema.ABAC.Domain.Entities.Resource", "Resource")
                        .WithMany("ResourceAttributes")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.UserAttribute", b =>
                {
                    b.HasOne("Sistema.ABAC.Domain.Entities.Attribute", "Attribute")
                        .WithMany("UserAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistema.ABAC.Domain.Entities.User", "User")
                        .WithMany("UserAttributes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.Action", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("PolicyActions");
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.Attribute", b =>
                {
                    b.Navigation("ResourceAttributes");

                    b.Navigation("UserAttributes");
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.Policy", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("Conditions");

                    b.Navigation("PolicyActions");
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.Resource", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("ResourceAttributes");
                });

            modelBuilder.Entity("Sistema.ABAC.Domain.Entities.User", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("UserAttributes");
                });
#pragma warning restore 612, 618
        }
    }
}
